name: multi job workflow

on: push

jobs:
  ubuntu-macos:     
    
    #strategy:
      #matrix:
        #os: [ubuntu-latest, macos-latest]
        
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5.5
        with:
          go-version: "1.20"
            
      - name: Build go
        run: go build -o main main.go
      - name: run go

        run: ./main

